add_newline = true

scan_timeout = 30
command_timeout = 500

format = """
$time - $username@$hostname:$directory $git_branch
$character
"""

[directory]
truncation_length = 0
truncate_to_repo = true
format = "[$path]($style)"

[git_branch]
always_show_remote = false
format = "[\\[$branch(:$remote_branch)\\]]($style) "

[hostname]
disabled = false
ssh_only = false
ssh_symbol = "\\[SSH\\]"
trim_at = "."
format = "[$hostname$ssh_symbol]($style)"

[time]
disabled = false
format = "[$time]($style)"
use_12hr = false

[username]
disabled = false
format = "[$user]($style)"
show_always = true
style_user = "bold yellow"
style_root = "bold red"

