require("maxstanley.packer")
require("maxstanley.color")
require("maxstanley.config")
require("maxstanley.config.display")
require("maxstanley.config.indentation")
require("maxstanley.config.spell")
require("maxstanley.config.search")
require("maxstanley.ide")
require("maxstanley.lsp")
require("maxstanley.keymap")
require("maxstanley.telescope")

-- local hour = tonumber(os.date("%H%M"))
-- print(hour)

